import { NextResponse } from 'next/server'
import type { Place } from '@/lib/mock-data'

// 전주 전역(한옥마을, 목판서화관, 강암서예관, 한벽문화관, 최명희문학관, 전통술박물관, 완판본문화관, 팔복예술공장, 덕진공원 등) 로컬 명소 DB
export const JEONJU_PLACES_DATABASE: Omit<Place, 'id' | 'order'>[] = [
  // --- [1] 📜 역사 문화재 & 네이버 지도 가볼만한곳 명소 (subCategory: 'spot' | 'museum') ---
  {
    name: '📜 전주 목판서화관 (목판 탁본 & 판화 체험관)',
    category: '📜 한옥마을 문화재 · 목판 서화관',
    subCategory: 'museum',
    suitableCompanions: ['couple', 'kids', 'family', 'friends', 'solo'],
    cost: 0,
    costLabel: '무료 관람 (탁본체험 3,000원)',
    walkMinutes: 5,
    reason: '전주 한옥마을 숨은 고즈넉 명소! 완판본 목판 서화 전시 감상 및 나만의 한지 목판 탁본 인쇄 체험을 즐기는 문화 공간입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 60,
    mapY: 56,
    lat: 35.8142,
    lng: 127.1530,
    address: '전북 전주시 완산구 은행로 26-6 (전주 한옥마을 내)',
    operatingHours: '10:00 - 18:00 (매주 월요일 휴무)',
    phone: '063-284-0570',
    tags: ['#전주목판서화관', '#목판체험', '#탁본인쇄', '#한옥마을문화재', '#무료실내관람'],
    suggestedDuration: '40분',
    tips: '💡 현지인 팁: 닥나무 한지 위에 먹물로 전통 목판 글귀를 직접 찍어내는 탁본 인쇄 체험(3,000원)이 매우 인기가 높습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주목판서화관',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "한옥마을입구" 하차 후 은행로 도보 4분',
    parkingInfo: '🚗 주차장: 한옥마을 제1·2 공영주차장 이용 권장',
    nearbyDining: [
      { name: '교동떡갈비', distance: '도보 2분 (140m)', menu: '숯불 수제 떡갈비 정식', naverMapUrl: 'https://map.naver.com/v5/search/교동떡갈비' },
      { name: '베테랑 칼국수', distance: '도보 3분 (210m)', menu: '들깨 칼국수, 수제 만두', naverMapUrl: 'https://map.naver.com/v5/search/베테랑칼국수' },
    ],
    nearbyCafes: [
      { name: '교동 다원', distance: '도보 2분 (120m)', menu: '전통 황차 & 잎차', naverMapUrl: 'https://map.naver.com/v5/search/교동다원' },
    ],
  },
  {
    name: '🖌️ 강암서예관 (전주 대표 서예 미술관)',
    category: '🖌️ 실내 · 서예 전문 미술관',
    subCategory: 'museum',
    suitableCompanions: ['couple', 'family', 'solo'],
    cost: 0,
    costLabel: '무료 관람',
    walkMinutes: 6,
    reason: '한국 서예의 대가 강암 송성용 선생의 대표 작품과 조선 명필 추사 김정희 서화가 보존된 전주천변 대표 서예 미술관입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 52,
    mapY: 66,
    lat: 35.8122,
    lng: 127.1528,
    address: '전북 전주시 완산구 현무1길 20 (전주천변 부근)',
    operatingHours: '09:00 - 18:00 (월요일 휴무)',
    phone: '063-284-1577',
    tags: ['#강암서예관', '#서예미술관', '#전주대표문화재', '#무료실내관람', '#전주천변'],
    suggestedDuration: '45분',
    tips: '💡 현지인 팁: 여름철이나 한파 때 조용하고 서늘하게 전주 서예 예술 거장들의 서화를 감상할 수 있는 힐링 스팟입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/강암서예관',
    transitInfo: '🚌 시내버스 190번, 684번 탑승 ➔ "남부시장" 하차 후 천변 도보 5분',
    parkingInfo: '🚗 주차장: 강암서예관 전용 주차장 및 천변 공영주차장 이용',
    nearbyDining: [
      { name: '한벽집 민물매운탕', distance: '도보 4분 (280m)', menu: '전주천 매운탕', naverMapUrl: 'https://map.naver.com/v5/search/한벽집' },
    ],
    nearbyCafes: [
      { name: '천변 뷰 고즈넉 카페', distance: '도보 2분 (110m)', menu: '핸드드립 커피', naverMapUrl: 'https://map.naver.com/v5/search/천변카페' },
    ],
  },
  {
    name: '🏛️ 전주 한벽문화관 (전주전통문화연수원)',
    category: '🏛️ 전통 한옥 문화 공간 · 공연장',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'family', 'kids', 'solo'],
    cost: 0,
    costLabel: '무료 관람 (공연/체험 별도)',
    walkMinutes: 7,
    reason: '한벽굴 근처 전주천을 끼고 형성된 고즈넉한 한옥 문화 단지로, 전통 공연과 예절/다도 체험 프로그램이 열립니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 75,
    mapY: 63,
    lat: 35.8118,
    lng: 127.1575,
    address: '전북 전주시 완산구 기린대로 20 (한벽터널 부근)',
    operatingHours: '09:00 - 18:00 (상시 관람 가능)',
    phone: '063-280-7000',
    tags: ['#한벽문화관', '#전통문화연수원', '#한옥공연장', '#다도체험', '#한벽굴근처'],
    suggestedDuration: '50분',
    tips: '💡 현지인 팁: 야외 마당 마루에 앉아 승암산 전경과 전주천 물소리를 감상하기 참 좋은 조용한 고즈넉 공간입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주한벽문화관',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "한벽굴·오목대" 하차 (도보 2분)',
    parkingInfo: '🚗 주차장: 한벽문화관 전용 공영주차장 이용 (무료)',
    nearbyDining: [
      { name: '한벽집 매운탕 노포', distance: '도보 1분 (60m)', menu: '민물 매운탕', naverMapUrl: 'https://map.naver.com/v5/search/한벽집' },
    ],
    nearbyCafes: [
      { name: '한벽 찻집', distance: '도보 2분 (120m)', menu: '수제 대추차 & 전통 한과', naverMapUrl: 'https://map.naver.com/v5/search/한벽찻집' },
    ],
  },
  {
    name: '🌿 최명희문학관 (소설 <혼불> 작가 문학관)',
    category: '🌿 실내 · 최명희 문학관',
    subCategory: 'museum',
    suitableCompanions: ['couple', 'friends', 'solo', 'family'],
    cost: 0,
    costLabel: '무료 관람',
    walkMinutes: 4,
    reason: '소설 <혼불>의 작가 최명희 선생의 친필 원고와 문학적 삶을 조명하는 한옥마을 중심의 아담한 문화 공간입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 42,
    mapY: 52,
    lat: 35.8152,
    lng: 127.1525,
    address: '전북 전주시 완산구 최명희길 29',
    operatingHours: '09:00 - 18:00 (월요일 휴무)',
    phone: '063-284-0570',
    tags: ['#최명희문학관', '#혼불', '#문학관실내', '#한옥마을문화관', '#1년뒤엽서쓰기'],
    suggestedDuration: '35분',
    tips: '💡 현지인 팁: 문학관 마당에서 "1년 뒤 나에게 보내는 느린 편지 엽서"를 직접 작성하여 우체통에 넣어보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/최명희문학관',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "전동성당" 하차 후 최명희길 도보 4분',
    parkingInfo: '🚗 주차장: 한옥마을 제1공영주차장 이용',
    nearbyDining: [
      { name: '베테랑 칼국수', distance: '도보 2분 (130m)', menu: '들깨 칼국수', naverMapUrl: 'https://map.naver.com/v5/search/베테랑' },
    ],
    nearbyCafes: [
      { name: '외할머니솜씨', distance: '도보 3분 (190m)', menu: '흑임자 팥빙수', naverMapUrl: 'https://map.naver.com/v5/search/외할머니솜씨' },
    ],
  },
  {
    name: '📜 전주 완판본문화관 (조선시대 한글목판 소설 박물관)',
    category: '📜 한글목판 박물관 · 문화재',
    subCategory: 'museum',
    suitableCompanions: ['family', 'kids', 'couple', 'solo'],
    cost: 0,
    costLabel: '무료 관람',
    walkMinutes: 6,
    reason: '조선 시대 전주에서 인쇄한 완판본 한글 고소설(춘향전, 심청전 등) 목판 인쇄 문화와 출판 역사를 배우는 박물관입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 70,
    mapY: 60,
    lat: 35.8120,
    lng: 127.1565,
    address: '전북 전주시 완산구 목원길 16-2 (한벽굴 부근)',
    operatingHours: '09:00 - 18:00 (월요일 휴무)',
    phone: '063-231-2212',
    tags: ['#완판본문화관', '#조선한글목판', '#고서박물관', '#역사체험', '#한벽굴근처'],
    suggestedDuration: '40분',
    tips: '💡 현지인 팁: 조선시대 완판본 한글 목판 제작 과정 영상을 시청하고 직접 인쇄해보는 체험이 알찹니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/완판본문화관',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "오목대·한벽굴" 하차 (도보 3분)',
    parkingInfo: '🚗 주차장: 완판본문화관 전용 주차장 및 한벽문화관 주차장',
    nearbyDining: [
      { name: '한벽집', distance: '도보 2분 (140m)', menu: '민물 매운탕', naverMapUrl: 'https://map.naver.com/v5/search/한벽집' },
    ],
    nearbyCafes: [
      { name: '한벽 찻집', distance: '도보 2분 (100m)', menu: '전통 차 & 오미자차', naverMapUrl: 'https://map.naver.com/v5/search/한벽찻집' },
    ],
  },
  {
    name: '🍵 전주 전통술박물관 (조선 가양주 시음 및 체험)',
    category: '🍵 실내 · 전통 가양주 박물관',
    subCategory: 'museum',
    suitableCompanions: ['couple', 'friends', 'solo'],
    cost: 0,
    costLabel: '무료 관람 (가양주 시음 3,000원)',
    walkMinutes: 5,
    reason: '집에서 빚던 조선 전통 가양주 선비 술 문화를 배우고, 모주 및 쌀막걸리를 시음해보는 한옥마을 이색 박물관입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 63,
    mapY: 54,
    lat: 35.8158,
    lng: 127.1545,
    address: '전북 전주시 완산구 한지길 74',
    operatingHours: '09:00 - 18:00 (월요일 휴무)',
    phone: '063-287-6305',
    tags: ['#전통술박물관', '#가양주시음', '#전주이색체험', '#술빚기체험', '#한옥마을핫플'],
    suggestedDuration: '45분',
    tips: '💡 현지인 팁: 따뜻하고 은은한 한옥 대청마루에서 전주 전통 모주와 청주 3종 시음 세트를 맛보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주전통술박물관',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "한옥마을입구" 하차 (한지길 도보 5분)',
    parkingInfo: '🚗 주차장: 한옥마을 제1·2 공영주차장 이용',
    nearbyDining: [
      { name: '교동떡갈비', distance: '도보 3분 (180m)', menu: '떡갈비 정식', naverMapUrl: 'https://map.naver.com/v5/search/교동떡갈비' },
    ],
    nearbyCafes: [
      { name: '교동 다원', distance: '도보 2분 (120m)', menu: '황차', naverMapUrl: 'https://map.naver.com/v5/search/교동다원' },
    ],
  },
  {
    name: '🏛️ 전주 풍남문 (조선시대 전주 읍성 사적지)',
    category: '🏛️ 역사 사적지 · 읍성 남문',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'family', 'friends', 'solo'],
    cost: 0,
    costLabel: '무료',
    walkMinutes: 3,
    reason: '조선시대 전주부성의 4대문 중 유일하게 남아있는 보물 제308호로, 남부시장 및 전동성당 바로 옆에 위치한 사적지입니다.',
    isMustVisit: false,
    isIndoor: false,
    mapX: 28,
    mapY: 60,
    lat: 35.8138,
    lng: 127.1475,
    address: '전북 전주시 완산구 풍남문3길 1',
    operatingHours: '상시 개방 (야간 웅장한 조명 점등)',
    phone: '063-281-2114',
    tags: ['#풍남문', '#전주읍성', '#보물제308호', '#남부시장근처', '#야경포토존'],
    suggestedDuration: '25분',
    tips: '💡 현지인 팁: 밤 7시 이후 조명이 밝혀질 때 성문 앞 광장에서 사진을 찍으면 웅장한 단청 조명이 예술입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/풍남문',
    transitInfo: '🚌 시내버스 684번, 104번 탑승 ➔ "풍남문" 정류장 하차 (도보 1분)',
    parkingInfo: '🚗 주차장: 남부시장 천변 주차장 및 풍남문 노상 주차구역',
    nearbyDining: [
      { name: '조점례 남부시장 피순대', distance: '도보 2분 (130m)', menu: '피순대', naverMapUrl: 'https://map.naver.com/v5/search/조점례피순대' },
    ],
    nearbyCafes: [
      { name: '풍남문 앞 테라스 카페', distance: '도보 1분 (50m)', menu: '아메리카노', naverMapUrl: 'https://map.naver.com/v5/search/풍남문카페' },
    ],
  },
  {
    name: '🎬 한벽굴 (한벽터널) - 드라마 스물다섯 스물하나 촬영지',
    category: '🎬 드라마 촬영지 · 한벽터널',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'friends', 'solo', 'pet'],
    cost: 0,
    costLabel: '무료',
    walkMinutes: 12,
    reason: '드라마 <스물다섯 스물하나>에서 김태리와 남주혁이 달렸던 인스타 인생샷 터널 포토존입니다.',
    isMustVisit: false,
    isIndoor: false,
    mapX: 78,
    mapY: 65,
    lat: 35.8115,
    lng: 127.1585,
    address: '전북 전주시 완산구 기린대로 2 (한벽굴)',
    operatingHours: '상시 개방',
    phone: '063-281-2114',
    tags: ['#스물다섯스물하나', '#드라마촬영지', '#한벽터널', '#인생샷포토존'],
    suggestedDuration: '35분',
    tips: '💡 팁: 초록빛 덩굴이 터널 입구를 감싸고 있어 유량교 방향에서 찍으면 청량한 청춘 영화 같은 샷이 완성됩니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/한벽굴',
    transitInfo: '🚌 시내버스 1000번, 190번 탑승 ➔ "한벽굴·오목대" 하차 (도보 2분)',
    parkingInfo: '🚗 주차장: 한벽문화관 주차장 및 천변 노상 주차구역 이용',
    nearbyDining: [
      { name: '한벽집 (전주천 매운탕 노포)', distance: '도보 2분 (120m)', menu: '전주천 민물매운탕', naverMapUrl: 'https://map.naver.com/v5/search/한벽집' },
    ],
    nearbyCafes: [
      { name: '한벽굴 앞 고즈넉 카페', distance: '도보 1분 (70m)', menu: '수제 청음료', naverMapUrl: 'https://map.naver.com/v5/search/한벽굴카페' },
    ],
  },
  {
    name: '🎨 자만벽화마을 (지브리 애니메이션 벽화 골목)',
    category: '🎨 레트로 벽화마을 · 지브리 포토존',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'friends', 'kids', 'solo'],
    cost: 0,
    costLabel: '무료',
    walkMinutes: 8,
    reason: '센과 치히로, 토토로, 레트로 애니메이션 벽화가 가득한 언덕 산골 마을 포토존입니다.',
    isMustVisit: false,
    isIndoor: false,
    mapX: 72,
    mapY: 55,
    lat: 35.8140,
    lng: 127.1580,
    address: '전북 전주시 완산구 자만동2길 22',
    operatingHours: '상시 개방',
    phone: '063-281-2114',
    tags: ['#자만벽화마을', '#지브리벽화', '#토토로', '#벽화골목', '#인생샷'],
    suggestedDuration: '45분',
    tips: '💡 팁: 언덕 위 레트로 갤러리 카페 야외 테라스에서 전주 한옥 기와지붕 전경을 한눈에 담아보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/자만벽화마을',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "오목대·자만벽화마을" 하차 (도보 3분)',
    parkingInfo: '🚗 주차장: 한옥마을 제2공영주차장 이용',
    nearbyDining: [
      { name: '자만동 비빔밥', distance: '도보 2분 (100m)', menu: '잔치국수', naverMapUrl: 'https://map.naver.com/v5/search/자만동맛집' },
    ],
    nearbyCafes: [
      { name: '꼬지따뽕', distance: '도보 1분 (30m)', menu: '디저트', naverMapUrl: 'https://map.naver.com/v5/search/꼬지따뽕' },
    ],
  },
  {
    name: '🎬 전주향교 & 400년 은행나무 (성균관 스캔들 촬영지)',
    category: '🎬 드라마 촬영지 · 역사 향교',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'family', 'friends', 'solo', 'pet'],
    cost: 0,
    costLabel: '무료',
    walkMinutes: 6,
    reason: '드라마 <성균관 스캔들> 촬영지! 수령 400년 된 웅장한 거대 은행나무와 한적한 대청마루가 인상적인 숨은 명소입니다.',
    isMustVisit: false,
    isIndoor: false,
    mapX: 68,
    mapY: 62,
    lat: 35.8125,
    lng: 127.1550,
    address: '전북 전주시 완산구 향교길 139',
    operatingHours: '09:00 - 18:00 (월요일 휴무)',
    phone: '063-288-4544',
    tags: ['#성균관스캔들', '#전주향교', '#400년은행나무', '#한적한명소'],
    suggestedDuration: '40분',
    tips: '💡 팁: 명륜당 앞 대청마루에 앉아 조용히 고목의 바람 소리를 들으며 휴식을 취해보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주향교',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "전주향교" 하차 (도보 2분)',
    parkingInfo: '🚗 주차장: 한옥마을 제1·2 공영주차장 이용 권장',
    nearbyDining: [
      { name: '향교길 백반', distance: '도보 3분 (180m)', menu: '백반 정식', naverMapUrl: 'https://map.naver.com/v5/search/향교길백반' },
    ],
    nearbyCafes: [
      { name: '향교 찻집', distance: '도보 2분 (120m)', menu: '수제 잎차', naverMapUrl: 'https://map.naver.com/v5/search/향교찻집' },
    ],
  },
  {
    name: '🏭 전주 팔복예술공장 (폐공장 개조 현대 미술관)',
    category: '🏭 힙한 복합문화공간 · 폐공장 미술관',
    subCategory: 'museum',
    suitableCompanions: ['couple', 'friends', 'kids', 'family', 'solo'],
    cost: 0,
    costLabel: '무료 관람',
    walkMinutes: 15,
    reason: '폐 카세트 공장을 힙한 현대 미술관과 레트로 철길, 인더스트리얼 카페로 재탄생시킨 전주 대표 문화 공장입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 15,
    mapY: 30,
    lat: 35.8520,
    lng: 127.1080,
    address: '전북 전주시 덕진구 구렛들1길 46 (팔복동1가)',
    operatingHours: '10:00 - 18:00 (월요일 휴무)',
    phone: '063-211-0288',
    tags: ['#팔복예술공장', '#힙한미술관', '#폐공장재생', '#무료전시'],
    suggestedDuration: '1시간 20분',
    tips: '💡 팁: 공장 사이를 잇는 붉은 컨테이너 브릿지와 야외 이팝나무 철길 산책로가 숨은 포토존입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/팔복예술공장',
    transitInfo: '🚌 시내버스 337번 탑승 ➔ "팔복예술공장" 정류장 하차 (도보 1분)',
    parkingInfo: '🚗 주차장: 팔복예술공장 전용 대형 공영주차장 (무료)',
    nearbyDining: [
      { name: '팔복동 수제비', distance: '도보 3분 (200m)', menu: '수제비', naverMapUrl: 'https://map.naver.com/v5/search/팔복동수제비' },
    ],
    nearbyCafes: [
      { name: '써니 카페', distance: '도보 1분 (30m)', menu: '팔복 라떼', naverMapUrl: 'https://map.naver.com/v5/search/써니카페' },
    ],
  },
  {
    name: '🌲 한국도로공사 전주 수목원 (온실 & 핑크뮬리)',
    category: '🌲 힐링 수목원 · 인생샷 온실',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'kids', 'family', 'solo', 'pet'],
    cost: 0,
    costLabel: '무료입장',
    walkMinutes: 20,
    reason: '입장료 무료! 웅장한 수중 유리 온실과 계절별 핑크뮬리, 대나무 숲길이 아름다운 전주 수목원입니다.',
    isMustVisit: false,
    isIndoor: false,
    mapX: 10,
    mapY: 15,
    lat: 35.8720,
    lng: 127.0580,
    address: '전북 전주시 덕진구 번영로 462-45',
    operatingHours: '09:00 - 18:00 (월요일 휴무)',
    phone: '063-714-3200',
    tags: ['#전주수목원', '#유리온실', '#무료수목원', '#핑크뮬리'],
    suggestedDuration: '1시간 30분',
    tips: '💡 팁: 수중식원 조형물 프레임 너머로 호수를 바라보는 명당 자리가 포토존입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주수목원',
    transitInfo: '🚌 시내버스 4000번 탑승 ➔ "전주수목원" 정류장 하차 (도보 3분)',
    parkingInfo: '🚗 주차장: 전주 수목원 대형 주차장 (무료)',
    nearbyDining: [
      { name: '수목원 닭볶음탕', distance: '차로 3분 (1.2km)', menu: '묵은지 닭볶음탕', naverMapUrl: 'https://map.naver.com/v5/search/수목원맛집' },
    ],
    nearbyCafes: [
      { name: '수목원 온실 카페', distance: '수목원 내 위치', menu: '아메리카노', naverMapUrl: 'https://map.naver.com/v5/search/수목원카페' },
    ],
  },
  {
    name: '🌊 아중호수 수중 산책로 & 야경 데크',
    category: '🌊 호수 수중산책로 · 힐링 야경',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'friends', 'solo', 'family', 'pet'],
    cost: 0,
    costLabel: '무료',
    walkMinutes: 15,
    reason: '잔잔한 호수 위를 걸어가는 나무 데크 수중 산책로로, 은은한 밤 조명 야경이 낭만적인 스팟입니다.',
    isMustVisit: false,
    isIndoor: false,
    mapX: 85,
    mapY: 45,
    lat: 35.8150,
    lng: 127.1850,
    address: '전북 전주시 덕진구 아중호수길 130',
    operatingHours: '상시 개방',
    phone: '063-281-2114',
    tags: ['#아중호수', '#수중산책로', '#전주야경', '#호수데크'],
    suggestedDuration: '50분',
    tips: '💡 팁: 해 질 무렵 노을이 호수에 반사되는 시간대에 산책하시면 낭만이 배가됩니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/아중호수',
    transitInfo: '🚌 시내버스 104번 탑승 ➔ "아중호수" 하차 (도보 2분)',
    parkingInfo: '🚗 주차장: 아중호수 공영주차장 (무료)',
    nearbyDining: [
      { name: '아중호수 매운탕', distance: '도보 3분 (200m)', menu: '참게탕', naverMapUrl: 'https://map.naver.com/v5/search/아중호수맛집' },
    ],
    nearbyCafes: [
      { name: '아중호수 뷰 카페', distance: '도보 2분 (120m)', menu: '아인슈페너', naverMapUrl: 'https://map.naver.com/v5/search/아중호수카페' },
    ],
  },
  {
    name: '📸 서학동 예술마을 (인스타 릴스 감성 골목)',
    category: '📸 인스타 릴스 핫플 · 예술 골목',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'friends', 'solo'],
    cost: 0,
    costLabel: '무료',
    walkMinutes: 10,
    reason: '예술가들의 공방, 독립서점, 레트로 갤러리가 모인 감성 서학동 골목입니다.',
    isMustVisit: false,
    isIndoor: false,
    mapX: 65,
    mapY: 72,
    lat: 35.8108,
    lng: 127.1520,
    address: '전북 전주시 완산구 서학로 16-17 일대',
    operatingHours: '상시 개방',
    phone: '063-281-2114',
    tags: ['#서학동예술마을', '#독립서점', '#감성골목'],
    suggestedDuration: '45분',
    tips: '💡 현지인 팁: 담쟁이덩굴이 뒤덮인 작은 사진관과 소품숍 앞에서 감성 사진을 찍어보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/서학동예술마을',
    transitInfo: '🚌 시내버스 190번 탑승 ➔ "서학동예술마을" 하차 (도보 1분)',
    parkingInfo: '🚗 주차장: 국립무형유산원 무료 주차장 이용',
    nearbyDining: [
      { name: '서학동 백반', distance: '도보 2분 (130m)', menu: '가정식 백반', naverMapUrl: 'https://map.naver.com/v5/search/서학동백반' },
    ],
    nearbyCafes: [
      { name: '서학동 독립서점 카페', distance: '도보 2분 (110m)', menu: '드립 커피', naverMapUrl: 'https://map.naver.com/v5/search/서학동카페' },
    ],
  },
  {
    name: '📚 덕진공원 연화정 한옥 도서관 (인스타 뷰 핫플)',
    category: '📚 📸 호수 뷰 한옥 도서관 · 인스타 핫플',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'kids', 'solo', 'family'],
    cost: 0,
    costLabel: '무료',
    walkMinutes: 15,
    reason: '덕진호수 연꽃 한가운데 떠있는 아름다운 한옥 도서관으로 힐링 핫플입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 20,
    mapY: 20,
    lat: 35.8475,
    lng: 127.1215,
    address: '전북 전주시 덕진구 권삼득로 390 (덕진공원 내부)',
    operatingHours: '10:00 - 19:00 (월요일 휴무)',
    phone: '063-281-6925',
    tags: ['#연화정도서관', '#호수뷰한옥', '#인스타핫플'],
    suggestedDuration: '1시간',
    tips: '💡 현지인 팁: 통창 너머로 덕진호수 물결을 감상하며 조용히 책을 읽을 수 있는 최고의 힐링 공간입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/연화정도서관',
    transitInfo: '🚌 시내버스 165번 탑승 ➔ "덕진공원" 하차 (도보 5분)',
    parkingInfo: '🚗 주차장: 덕진공원 공영주차장 (무료)',
    nearbyDining: [
      { name: '덕진 콩나물국밥', distance: '도보 4분 (260m)', menu: '콩나물국밥', naverMapUrl: 'https://map.naver.com/v5/search/덕진공원국밥' },
    ],
    nearbyCafes: [
      { name: '연화정 호수 카페', distance: '도보 1분 (50m)', menu: '말차 라떼', naverMapUrl: 'https://map.naver.com/v5/search/연화정카페' },
    ],
  },
  {
    name: '🧸 전주 난장 7080 실내 체험 박물관',
    category: '🧸 아이/친구 강추 · 레트로 실내 체험',
    subCategory: 'activity',
    suitableCompanions: ['kids', 'friends', 'family'],
    cost: 7500,
    costLabel: '7,500원',
    walkMinutes: 7,
    reason: '80여 개의 추억의 옛날 교실, 오락실, 구멍가게를 만지고 즐기는 체험 박물관입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 45,
    mapY: 48,
    lat: 35.8165,
    lng: 127.1515,
    address: '전북 전주시 완산구 동문길 33-20',
    operatingHours: '10:00 - 19:00',
    phone: '063-288-0050',
    tags: ['#전주난장', '#아이체험강추', '#레트로감성'],
    suggestedDuration: '1시간',
    tips: '💡 현지인 팁: 옛날 달고나 만들기 체험과 추억의 오락실 게임기를 무료로 즐길 수 있습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주난장',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "동문길" 하차 (도보 3분)',
    parkingInfo: '🚗 주차장: 한옥마을 제1공영주차장 이용 권장',
    nearbyDining: [
      { name: '베테랑 칼국수', distance: '도보 3분 (200m)', menu: '칼국수', naverMapUrl: 'https://map.naver.com/v5/search/베테랑칼국수' },
    ],
    nearbyCafes: [
      { name: '추억의 달고나 카페', distance: '도보 1분 (30m)', menu: '달고나 라떼', naverMapUrl: 'https://map.naver.com/v5/search/달고나카페' },
    ],
  },
  {
    name: '🤫 남부시장 청년몰 (현지인 숨은 핫플)',
    category: '🤫 현지인 숨은 핫플 · 청년몰 레트로',
    subCategory: 'activity',
    suitableCompanions: ['friends', 'couple', 'solo'],
    cost: 0,
    costLabel: '무료 (구매 시 개별)',
    walkMinutes: 11,
    reason: '남부시장 2층에 숨겨진 현지인 핫플! 핸드메이드 소품숍, 독립 서점과 카페가 모여있습니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 74,
    mapY: 42,
    lat: 35.8122,
    lng: 127.1465,
    address: '전북 전주시 완산구 풍남문2길 53 (남부시장 2층)',
    operatingHours: '12:00 - 20:00 (월요일 휴무)',
    phone: '063-284-1344',
    tags: ['#청년몰', '#현지인핫플', '#레트로소품'],
    suggestedDuration: '45분',
    tips: '💡 현지인 팁: "적당히 벌고 아주 잘 살자" 입구 포토존에서 힙한 사진을 찍어보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/남부시장청년몰',
    transitInfo: '🚌 시내버스 684번 탑승 ➔ "남부시장" 하차 (도보 2분)',
    parkingInfo: '🚗 주차장: 남부시장 천변 공영주차장 이용',
    nearbyDining: [
      { name: '조점례 남부시장 피순대', distance: '도보 1분 (70m)', menu: '피순대', naverMapUrl: 'https://map.naver.com/v5/search/조점례피순대' },
    ],
    nearbyCafes: [
      { name: '청년몰 레트로 카페', distance: '도보 1분 (40m)', menu: '드립 커피', naverMapUrl: 'https://map.naver.com/v5/search/청년몰카페' },
    ],
  },
  {
    name: '전동성당',
    category: '🏛️ 실내외 · 역사 명소',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'friends', 'family', 'solo', 'pet'],
    cost: 0,
    costLabel: '무료',
    walkMinutes: 0,
    reason: '전주의 상징적 역사 사적지이자 인생샷을 남기는 로맨틱 비잔틴 양식 성당입니다.',
    isMustVisit: true,
    isIndoor: true,
    mapX: 30,
    mapY: 62,
    lat: 35.8133,
    lng: 127.1492,
    address: '전북 전주시 완산구 태조로 51',
    operatingHours: '09:00 - 17:00',
    phone: '063-284-3222',
    tags: ['#사적지', '#사진맛집', '#비잔틴양식'],
    suggestedDuration: '30분',
    tips: '💡 현지인 팁: 뒤편 사제관 건물과 성모상 앞 정원이 숨은 포토존입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전동성당',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "전동성당" 하차 (도보 2분)',
    parkingInfo: '🚗 주차장: 한옥마을 제1공영주차장 이용',
    nearbyDining: [
      { name: '한국집', distance: '도보 3분 (220m)', menu: '비빔밥', naverMapUrl: 'https://map.naver.com/v5/search/한국집' },
    ],
    nearbyCafes: [
      { name: '한옥마을 찻집', distance: '도보 4분 (250m)', menu: '쌍화차', naverMapUrl: 'https://map.naver.com/v5/search/한옥마을찻집' },
    ],
  },
  {
    name: '경기전 & 대나무 숲길',
    category: '🏛️ 실외 · 역사 문화',
    subCategory: 'spot',
    suitableCompanions: ['couple', 'family', 'friends', 'solo', 'pet'],
    cost: 3000,
    costLabel: '3,000원',
    walkMinutes: 4,
    reason: '태조 이성계 어진과 함께 한복 입고 사진 찍는 청량한 대나무 숲길이 유명합니다.',
    isMustVisit: true,
    isIndoor: false,
    mapX: 38,
    mapY: 55,
    lat: 35.8150,
    lng: 127.1498,
    address: '전북 전주시 완산구 태조로 44',
    operatingHours: '09:00 - 19:00',
    phone: '063-281-2790',
    tags: ['#어진박물관', '#대나무숲', '#한복촬영'],
    suggestedDuration: '1시간',
    tips: '💡 현지인 팁: 대나무 숲길 사이로 햇빛이 비치는 정원이 사진 스팟입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/경기전',
    transitInfo: '🚌 시내버스 1000번 탑승 ➔ "전동성당" 하차 (도보 3분)',
    parkingInfo: '🚗 주차장: 한옥마을 공영주차장 이용',
    nearbyDining: [
      { name: '교동떡갈비', distance: '도보 4분 (270m)', menu: '떡갈비', naverMapUrl: 'https://map.naver.com/v5/search/교동떡갈비' },
    ],
    nearbyCafes: [
      { name: '외할머니솜씨', distance: '도보 4분 (280m)', menu: '팥빙수', naverMapUrl: 'https://map.naver.com/v5/search/외할머니솜씨' },
    ],
  },
]

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const q = searchParams.get('q')?.trim() ?? ''

  if (!q) {
    return NextResponse.json(JEONJU_PLACES_DATABASE.slice(0, 10))
  }

  const matched = JEONJU_PLACES_DATABASE.filter(
    (p) =>
      p.name.toLowerCase().includes(q.toLowerCase()) ||
      p.category.toLowerCase().includes(q.toLowerCase()) ||
      p.address?.toLowerCase().includes(q.toLowerCase()) ||
      p.tags?.some((t) => t.toLowerCase().includes(q.toLowerCase())),
  )

  if (!matched.some((p) => p.name === q)) {
    const customSearchPlace: Omit<Place, 'id' | 'order'> = {
      name: q,
      category: '네이버 지도 검색 장소',
      subCategory: 'spot',
      cost: 0,
      costLabel: '입장료/비용 개별 확인',
      walkMinutes: 10,
      reason: `사용자께서 직접 검색하여 추가하신 필수 방문지 '${q}'입니다.`,
      isMustVisit: true,
      isIndoor: true,
      mapX: Math.floor(Math.random() * 40) + 30,
      mapY: Math.floor(Math.random() * 40) + 30,
      lat: 35.8140 + (Math.random() * 0.006 - 0.003),
      lng: 127.1510 + (Math.random() * 0.006 - 0.003),
      address: `전북 전주시 완산구 ${q} 부근 (네이버 지도 검색)`,
      operatingHours: '운영시간 개별 확인',
      phone: '네이버 지도 참조',
      tags: ['#직접검색추가', '#필수방문지', '#네이버지도'],
      suggestedDuration: '45분',
      tips: `💡 현지인 팁: 네이버 지도를 통해 '${q}'의 최신 휴무일과 실시간 방문 후기를 확인하세요.`,
      naverMapUrl: `https://map.naver.com/v5/search/${encodeURIComponent(q)}`,
      transitInfo: `🚌 시내버스 노선은 네이버 지도의 최신 버스 정보를 참조해 주세요.`,
      parkingInfo: `🚗 인근 공영/민영 주차장을 이용해 주세요.`,
    }
    return NextResponse.json([customSearchPlace, ...matched].slice(0, 10))
  }

  return NextResponse.json(matched.slice(0, 10))
}
