import { NextResponse } from 'next/server'
import type { Place } from '@/lib/mock-data'

// 전주 대표 로컬 액티비티 / 명소 및 네이버 지도 연동 맛집 데이터베이스
export const JEONJU_PLACES_DATABASE: Omit<Place, 'id' | 'order'>[] = [
  // --- [1] 역사 & 명소 ---
  {
    name: '전동성당',
    category: '실내 · 역사 명소',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 0,
    reason: '현재 위치에서 가장 가까운 전주의 대표 역사 사적지입니다.',
    isMustVisit: true,
    mapX: 30,
    mapY: 62,
    address: '전북 전주시 완산구 태조로 51',
    operatingHours: '09:00 - 17:00 (일요일 미사 시간 제외)',
    phone: '063-284-3222',
    tags: ['#사적지', '#사진맛집', '#비잔틴양식', '#한옥마을입구'],
    suggestedDuration: '30분',
    tips: '💡 현지인 팁: 성당 본당 정면도 예쁘지만, 뒤편 사제관 건물과 성모상 앞 정원이 한적한 숨은 포토존입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20전동성당',
  },
  {
    name: '경기전',
    category: '실외 · 역사 문화',
    cost: 3000,
    costLabel: '3,000원',
    walkMinutes: 4,
    reason: '태조 이성계의 어진이 모셔진 곳으로, 대나무 숲길 산책이 매력적인 장소입니다.',
    isMustVisit: true,
    mapX: 38,
    mapY: 55,
    address: '전북 전주시 완산구 태조로 44',
    operatingHours: '09:00 - 19:00 (입장마감 18:00)',
    phone: '063-281-2790',
    tags: ['#어진박물관', '#대나무숲', '#한복체험필수', '#역사탐방'],
    suggestedDuration: '1시간',
    tips: '💡 현지인 팁: 경기전 내 대나무 숲길은 한복 입고 사진 찍기에 가장 인기 있는 명소입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20경기전',
  },
  {
    name: '전주향교',
    category: '실외 · 문화재 산책',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 10,
    reason: '수령 400년이 넘는 거대 은행나무와 고풍스러운 대성전이 어우러진 조용한 스팟입니다.',
    isMustVisit: false,
    mapX: 52,
    mapY: 70,
    address: '전북 전주시 완산구 향교길 139',
    operatingHours: '09:00 - 18:00 (동절기 17:00까지)',
    phone: '063-288-4544',
    tags: ['#은행나무', '#성균관스캔들촬영지', '#무료입장', '#고즈넉산책'],
    suggestedDuration: '40분',
    tips: '💡 현지인 팁: 고풍스러운 한옥 담장 아래에서 한적하게 산책하기 최고의 명소입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주향교',
  },
  {
    name: '오목대',
    category: '실외 · 전망 명소',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 8,
    reason: '한옥마을 전체 기와지붕 풍경을 한눈에 내려다볼 수 있는 대표 전망 포인트입니다.',
    isMustVisit: false,
    mapX: 50,
    mapY: 35,
    address: '전북 전주시 완산구 기린대로 55',
    operatingHours: '24시간 상시 개방',
    phone: '063-281-2114',
    tags: ['#한옥전망', '#야경명소', '#산책로', '#이성계'],
    suggestedDuration: '30분',
    tips: '💡 현지인 팁: 해 질 녘 오목대 전망대에 오르면 주황빛 노을과 한옥마을 야경을 감상할 수 있습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20오목대',
  },
  {
    name: '자만벽화마을',
    category: '실외 · 예술 골목',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 14,
    reason: '오목대 건너편 산자락 골목에 알록달록한 아기자기한 벽화와 전망 좋은 카페들이 모여있습니다.',
    isMustVisit: false,
    mapX: 82,
    mapY: 65,
    address: '전북 전주시 완산구 자만동2길 22',
    operatingHours: '상시 개방',
    phone: '063-281-2555',
    tags: ['#골목벽화', '#전망카페', '#사진스팟', '#레트로감성'],
    suggestedDuration: '50분',
    tips: '💡 현지인 팁: 골목 상단의 디저트 카페테라스 전망에서 한옥마을 전체 뷰를 배경으로 사진을 찍어보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/자만벽화마을',
  },

  // --- [2] 네이버 지도 연동 유명 점심/미식 맛집 (Restaurant / Food) ---
  {
    name: '한국집 (전주 3대 비빔밥)',
    category: '🍽️ 네이버 지도 추천 · 점심 식사',
    cost: 15000,
    costLabel: '15,000원',
    walkMinutes: 5,
    reason: '미슐랭 가이드에 등재된 70년 전통의 전주 전통 육회비빔밥 맛집입니다.',
    isMustVisit: false,
    isMeal: true,
    mapX: 35,
    mapY: 50,
    address: '전북 전주시 완산구 어진길 119',
    operatingHours: '09:30 - 21:00 (브레이크타임 16:00 - 17:00)',
    phone: '063-284-2230',
    tags: ['#전주비빔밥', '#미슐랭가이드', '#육회비빔밥', '#점심추천'],
    suggestedDuration: '50분',
    tips: '💡 네이버 지도 점심 팁: 놋그릇에 따뜻하게 담겨 나오는 육회비빔밥과 정갈한 반찬 구성이 훌륭합니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20한국집',
  },
  {
    name: '현대옥 한옥마을점 (콩나물국밥)',
    category: '🍽️ 네이버 지도 추천 · 점심/식사',
    cost: 9000,
    costLabel: '9,000원',
    walkMinutes: 7,
    reason: '남부시장식 수란과 함께 즐기는 전주 콩나물국밥의 대표 식당입니다.',
    isMustVisit: false,
    isMeal: true,
    mapX: 42,
    mapY: 45,
    address: '전북 전주시 완산구 오목대길 66',
    operatingHours: '08:00 - 20:00 (연중무휴)',
    phone: '063-285-8989',
    tags: ['#콩나물국밥', '#남부시장식', '#수란', '#든든한식사'],
    suggestedDuration: '40분',
    tips: '💡 네이버 지도 점심 팁: 수란에 국물 3~4숟가락과 김을 찢어 넣어 먼저 드신 후 국밥을 즐기세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/현대옥%20한옥마을점',
  },
  {
    name: '조점례 남부시장 피순대',
    category: '🍽️ 네이버 지도 추천 · 점심/저녁 미식',
    cost: 10000,
    costLabel: '10,000원',
    walkMinutes: 12,
    reason: '속이 꽉 찬 수제 피순대와 얼큰한 순대국밥으로 전국적인 명성을 얻은 전주 미식 스팟입니다.',
    isMustVisit: false,
    isMeal: true,
    mapX: 75,
    mapY: 42,
    address: '전북 전주시 완산구 풍남문2길 39 (남부시장 내)',
    operatingHours: '24시간 영업 (연중무휴)',
    phone: '063-288-1439',
    tags: ['#피순대', '#순대국밥', '#남부시장맛집', '#TV출연맛집'],
    suggestedDuration: '50분',
    tips: '💡 네이버 지도 점심 팁: 깻잎에 피순대와 릿한 깻잎 향, 초장을 올려 싸 드시는 것이 전주 현지 방식입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/조점례%20남부시장%20피순대',
  },
  {
    name: '교동떡갈비',
    category: '🍽️ 네이버 지도 추천 · 떡갈비 점심',
    cost: 16000,
    costLabel: '16,000원',
    walkMinutes: 6,
    reason: '숯불 향 가득한 수제 떡갈비와 전주 비빔밥 세트를 쾌적한 한옥 공간에서 즐기는 맛집입니다.',
    isMustVisit: false,
    isMeal: true,
    mapX: 48,
    mapY: 52,
    address: '전북 전주시 완산구 은행로 52',
    operatingHours: '11:00 - 20:30 (라스트오더 19:50)',
    phone: '063-288-2232',
    tags: ['#수제떡갈비', '#한옥맛집', '#점심세트', '#가족추천'],
    suggestedDuration: '55분',
    tips: '💡 네이버 지도 점심 팁: 런치 시간대 떡갈비+미니비빔밥 정식 세트 구성의 가성비가 뛰어납니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20교동떡갈비',
  },
  {
    name: '객리단길 서양식당 (파스타 & 샐러드)',
    category: '🍽️ 네이버 지도 추천 · 감성 점심',
    cost: 17000,
    costLabel: '17,000원대',
    walkMinutes: 16,
    reason: '객리단길의 감성적인 분위기 속에서 이색 레트로 파스타와 스테이크를 즐길 수 있는 곳입니다.',
    isMustVisit: false,
    isMeal: true,
    mapX: 22,
    mapY: 28,
    address: '전북 전주시 완산구 객사3길 50',
    operatingHours: '11:30 - 21:30 (브레이크타임 15:00 - 17:00)',
    phone: '063-283-9988',
    tags: ['#객리단길', '#파스타맛집', '#데이트점심', '#분위기 짱'],
    suggestedDuration: '1시간',
    tips: '💡 네이버 지도 점심 팁: 데이트나 친구와 함께 감성 사진을 찍으며 여유로운 점심을 즐기기 좋습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20객리단길%20파스타',
  },

  // --- [3] 디저트 & 다과 & 길거리 먹거리 ---
  {
    name: '한옥마을 전통찻집',
    category: '실내 · 감성 카페',
    cost: 9000,
    costLabel: '9,000원',
    walkMinutes: 6,
    reason: '고즈넉한 한옥 마당을 바라보며 쌍화차와 유과를 즐길 수 있는 힐링 공간입니다.',
    isMustVisit: false,
    mapX: 46,
    mapY: 48,
    address: '전북 전주시 완산구 은행로 65-1',
    operatingHours: '10:00 - 22:00 (연중무휴)',
    phone: '063-282-1234',
    tags: ['#전통차', '#쌍화차', '#마당정원', '#고즈넉함'],
    suggestedDuration: '45분',
    tips: '💡 현지인 팁: 툇마루 자리에 앉아 고즈넉한 한옥 마당을 바라보며 수제 유과와 한방차를 즐겨보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20한옥마을%20전통찻집',
  },
  {
    name: '길거리야 바게트버거',
    category: '🍢 디저트 · 로컬 특색 간식',
    cost: 5500,
    costLabel: '5,500원',
    walkMinutes: 5,
    reason: '매콤달콤한 고기와 야채가 바삭한 바게트 속을 가득 채운 전주 명물 간식입니다.',
    isMustVisit: false,
    mapX: 36,
    mapY: 58,
    address: '전북 전주시 완산구 경기전길 124',
    operatingHours: '09:30 - 20:30 (재료 소진 시 조기마감)',
    phone: '063-286-5533',
    tags: ['#바게트버거', '#전주명물', '#포장간식', '#가성비'],
    suggestedDuration: '20분',
    tips: '💡 현지인 팁: 테이크아웃하여 한옥마을 산책을 하며 드시기 좋은 별미 간식입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20길거리야',
  },
  {
    name: '외할머니솜씨 (흑임자 팥빙수)',
    category: '🍧 전통 디저트 카페',
    cost: 8000,
    costLabel: '8,000원',
    walkMinutes: 8,
    reason: '고소한 흑임자와 국내산 팥이 듬뿍 들어간 전주 한옥마을 1세대 대표 디저트 카페입니다.',
    isMustVisit: false,
    mapX: 55,
    mapY: 50,
    address: '전북 전주시 완산구 오목대길 81-8',
    operatingHours: '11:00 - 21:00 (월요일 휴무)',
    phone: '063-232-5804',
    tags: ['#흑임자빙수', '#한옥카페', '#블루리본', '#전통디저트'],
    suggestedDuration: '40분',
    tips: '💡 현지인 팁: 시그니처 메뉴인 옛날 흑임자 팥빙수와 고소한 홍시 보숭이를 함께 맛보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20외할머니솜씨',
  },

  // --- [4] 체험 & 박물관 & 문화 ---
  {
    name: '수제 한지 공방 체험',
    category: '실내 · 로컬 체험',
    cost: 18000,
    costLabel: '18,000원',
    walkMinutes: 9,
    reason: '전주 닥나무 한지를 직접 뜨고 조명/엽서를 만들어보는 전주 전통 액티비티입니다.',
    isMustVisit: false,
    mapX: 62,
    mapY: 58,
    address: '전북 전주시 완산구 한지길 32',
    operatingHours: '10:00 - 18:00 (매주 월요일 휴무)',
    phone: '063-288-5678',
    tags: ['#한지공예', '#이색체험', '#실내액티비티', '#기념품만들기'],
    suggestedDuration: '1시간 15분',
    tips: '💡 현지인 팁: 직접 만든 한지 엽서는 당일 말려서 예쁜 봉투에 담아 기념품으로 가져가실 수 있습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20한지체험관',
  },
  {
    name: '전주 난장',
    category: '실내외 · 레트로 체험 박물관',
    cost: 7500,
    costLabel: '7,500원',
    walkMinutes: 7,
    reason: '7080 시절 추억의 학교, 빵집, 오락실 등을 그 시절 그대로 재현한 대형 체험 박물관입니다.',
    isMustVisit: false,
    mapX: 40,
    mapY: 60,
    address: '전북 전주시 완산구 동문길 33.20',
    operatingHours: '10:00 - 19:30 (토/일 20:00까지)',
    phone: '063-287-5005',
    tags: ['#레트로', '#추억의박물관', '#체험존', '#사진만장'],
    suggestedDuration: '1시간',
    tips: '💡 현지인 팁: 80가지가 넘는 테마존이 이어져 있어 부모님이나 친구와 함께 추억 사진 남기기에 제격입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20난장',
  },
  {
    name: '국립무형유산원',
    category: '실내 · 국립 문화 전시',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 12,
    reason: '대한민국 무형유산의 역사와 전통 장인들의 작품을 관람하고 이색 체험을 즐기는 공간입니다.',
    isMustVisit: false,
    mapX: 58,
    mapY: 75,
    address: '전북 전주시 완산구 서학로 95',
    operatingHours: '09:30 - 17:30 (매주 월요일 휴무)',
    phone: '063-280-1400',
    tags: ['#무형유산', '#무료전시', '#전통공예', '#쾌적한실내'],
    suggestedDuration: '1시간 10분',
    tips: '💡 현지인 팁: 쾌적하고 조용한 관람 환경을 자랑하며 전주천 다리를 건너며 산책하기에 좋습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/국립무형유산원',
  },
  {
    name: '전주 수목원 (한국도로공사 수목원)',
    category: '실외 · 수목원 명소',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 30,
    reason: '인스타 핫스팟으로 유명한 포토존 수생식물원과 기와 정원이 아름다운 수목원입니다.',
    isMustVisit: false,
    mapX: 12,
    mapY: 8,
    address: '전북 전주시 덕진구 번영로 462-45',
    operatingHours: '09:00 - 18:00 (월요일 휴무)',
    phone: '063-219-7114',
    tags: ['#전주수목원', '#인생샷포토존', '#수생식물원', '#무료수목원'],
    suggestedDuration: '1시간 30분',
    tips: '💡 현지인 팁: 수생식물원의 한옥 기와 프레임 포토존에서 줄 서서 인생샷을 꼭 남겨보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/한국도로공사%20전주수목원',
  },
  {
    name: '덕진공원',
    category: '실외 · 수변 공원 명소',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 25,
    reason: '거대한 연못 위에 자리 잡은 한옥 도서관 연화정과 수변 산책로가 우아한 공원입니다.',
    isMustVisit: false,
    mapX: 15,
    mapY: 15,
    address: '전북 전주시 덕진구 권삼득로 390',
    operatingHours: '24시간 개방 (연화정 도서관 10:00 - 19:00)',
    phone: '063-239-2607',
    tags: ['#연화당도서관', '#연꽃명소', '#수변산책', '#전주랜드마크'],
    suggestedDuration: '1시간 20분',
    tips: '💡 현지인 팁: 호수 한가운데 한옥 도서관 연화당 창가 자리에 앉아 힐링 독서를 즐기세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20덕진공원',
  },
  {
    name: '팔복예술공장',
    category: '실내외 · 복합 문화 예술 공간',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 30,
    reason: '카세트테이프 공장을 개조해 만든 힙한 현대미술 전시관 및 카페 공간입니다.',
    isMustVisit: false,
    mapX: 10,
    mapY: 10,
    address: '전북 전주시 덕진구 구렛들1길 46',
    operatingHours: '10:00 - 18:00 (매주 월요일 휴무)',
    phone: '063-211-0288',
    tags: ['#현대미술전시', '#재생건축', '#이색카페', '#문화예술'],
    suggestedDuration: '1시간 15분',
    tips: '💡 현지인 팁: 붉은 벽돌과 철제 구조물이 어우러진 야외 컨테이너 옥상 정원이 인더스트리얼 뷰 스팟입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20팔복예술공장',
  },
  {
    name: '아중호수 수변 산책로',
    category: '실외 · 호수 야경 산책',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 20,
    reason: '호수 둘레길을 따라 조성된 데크길과 밤에 켜지는 은은한 경관 조명이 로맨틱한 산책로입니다.',
    isMustVisit: false,
    mapX: 85,
    mapY: 20,
    address: '전북 전주시 덕진구 아중호수길 66',
    operatingHours: '24시간 개방',
    phone: '063-281-2114',
    tags: ['#호수산책', '#야경명소', '#수상데크길', '#로맨틱데이트'],
    suggestedDuration: '50분',
    tips: '💡 현지인 팁: 시원한 밤바람을 맞으며 수상 데크길을 걷는 야간 데이트 코스로 강력 추천합니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/아중호수',
  },
]

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const q = searchParams.get('q')?.trim() ?? ''

  if (!q) {
    return NextResponse.json(JEONJU_PLACES_DATABASE.slice(0, 8))
  }

  const matched = JEONJU_PLACES_DATABASE.filter(
    (p) =>
      p.name.toLowerCase().includes(q.toLowerCase()) ||
      p.category.toLowerCase().includes(q.toLowerCase()) ||
      p.address?.toLowerCase().includes(q.toLowerCase()) ||
      p.tags?.some((t) => t.toLowerCase().includes(q.toLowerCase())),
  )

  if (!matched.some((p) => p.name === q)) {
    const customSearchPlace: Omit<Place, 'id' | 'order'> = {
      name: q,
      category: '네이버 지도 검색 장소',
      cost: 0,
      costLabel: '입장료/비용 개별 확인',
      walkMinutes: 10,
      reason: `사용자께서 직접 검색하여 추가하신 필수 방문지 '${q}'입니다.`,
      isMustVisit: true,
      mapX: Math.floor(Math.random() * 40) + 30,
      mapY: Math.floor(Math.random() * 40) + 30,
      address: `전북 전주시 완산구 ${q} 부근 (네이버 지도 검색)`,
      operatingHours: '운영시간 개별 확인',
      phone: '네이버 지도 참조',
      tags: ['#직접검색추가', '#필수방문지', '#네이버지도'],
      suggestedDuration: '45분',
      tips: `💡 현지인 팁: 네이버 지도를 통해 '${q}'의 최신 휴무일과 실시간 방문 후기를 확인하세요.`,
      naverMapUrl: `https://map.naver.com/v5/search/${encodeURIComponent(q)}`,
    }
    return NextResponse.json([customSearchPlace, ...matched].slice(0, 8))
  }

  return NextResponse.json(matched.slice(0, 8))
}
