import { NextResponse } from 'next/server'
import type { Place } from '@/lib/mock-data'

// 전주 대표 로컬 액티비티 / 명소 및 네이버 지도 연동 맛집/이동수단 정보 데이터베이스
export const JEONJU_PLACES_DATABASE: Omit<Place, 'id' | 'order'>[] = [
  // --- [1] 시원한 실내 공방 & 체험 (더운 날씨/우천 최적 추천) ---
  {
    name: '수제 한지 공방 체험',
    category: '🎨 시원한 실내 · 로컬 한지 공방',
    cost: 18000,
    costLabel: '18,000원',
    walkMinutes: 6,
    reason: '무더운 날씨를 피해 시원한 실내에서 전주 닥나무 한지를 뜨고 한지 조명/엽서를 만드는 공방입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 62,
    mapY: 58,
    address: '전북 전주시 완산구 한지길 32',
    operatingHours: '10:00 - 18:00 (매주 월요일 휴무)',
    phone: '063-288-5678',
    tags: ['#한지공예', '#시원한실내', '#이색공방체험', '#기념품만들기'],
    suggestedDuration: '1시간 15분',
    tips: '💡 팁: 시원한 실내 에어컨 아래에서 나만의 정성 어린 한지 엽서와 거울을 직접 만들어 가실 수 있습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20한지체험관',
    transitInfo: '🚌 시내버스 1000번, 119번 탑승 ➔ "한옥마을입구" 하차 후 한지길 도보 4분',
    parkingInfo: '🚗 주차장: 한옥마을 제1공영주차장 이용 권장 (도보 5분)',
  },
  {
    name: '전주 부채 만들기 공방 (동문 부채공방)',
    category: '🎨 시원한 실내 · 한옥 부채 공방',
    cost: 14000,
    costLabel: '14,000원',
    walkMinutes: 5,
    reason: '폭염 날씨 필수템! 전주 전통 합죽선 부채에 캘리그라피와 먹 그림을 새겨보는 시원한 실내 공방입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 44,
    mapY: 62,
    address: '전북 전주시 완산구 동문길 45',
    operatingHours: '10:00 - 19:00 (연중무휴)',
    phone: '063-283-7722',
    tags: ['#부채공방', '#시원한에어컨', '#합죽선만들기', '#실내피서'],
    suggestedDuration: '50분',
    tips: '💡 팁: 더위를 시켜줄 자신만의 수제 부채를 완성하여 여행 내내 유용하게 쓰실 수 있습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20부채공방',
    transitInfo: '🚌 시내버스 1000번, 535번 탑승 ➔ "동문길" 하차 (도보 2분)',
    parkingInfo: '🚗 주차장: 동문길 민영주차장 및 한옥마을 공영주차장 이용',
  },
  {
    name: '전주 도자기 & 도예 힐링 공방',
    category: '🎨 시원한 실내 · 도예 체험 공방',
    cost: 20000,
    costLabel: '20,000원',
    walkMinutes: 8,
    reason: '시원한 감촉의 흙을 만지며 한옥 머그잔과 귀여운 캐릭터 접시를 물레로 만들어보는 힐링 공방입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 58,
    mapY: 52,
    address: '전북 전주시 완산구 은행로 40',
    operatingHours: '10:30 - 18:30 (매주 화요일 휴무)',
    phone: '063-285-1102',
    tags: ['#도예공방', '#물레체험', '#실내데이트', '#커플공방'],
    suggestedDuration: '1시간 10분',
    tips: '💡 팁: 완성된 도자기 작품은 구워서 3주 후 택배로 집까지 안심 발송해 드립니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20도자기공방',
    transitInfo: '🚌 시내버스 1000번, 119번 탑승 ➔ "전동성당" 하차 (은행로 도보 6분)',
    parkingInfo: '🚗 주차장: 한옥마을 제2공영주차장 도보 5분',
  },
  {
    name: '어진박물관 (경기전 지하 실내 전시관)',
    category: '🏛️ 시원한 실내 · 에어컨 박물관',
    cost: 0,
    costLabel: '경기전 입장권 포함 (무료)',
    walkMinutes: 4,
    reason: '경기전 지하에 위치한 초쾌적 실내 에어컨 박물관으로 조선 태조 어진과 왕실 유물을 서늘하게 관람합니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 39,
    mapY: 56,
    address: '전북 전주시 완산구 태조로 44 (경기전 내부 지하)',
    operatingHours: '09:00 - 18:00 (연중무휴)',
    phone: '063-281-2790',
    tags: ['#어진박물관', '#시원한지하박물관', '#에어컨빵빵', '#역사관람'],
    suggestedDuration: '45분',
    tips: '💡 팁: 야외 땡볕을 피해 경기전 안쪽 지하고 진입하시면 빵빵한 에어컨 바람 속에서 왕실 어진을 관람하실 수 있습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/어진박물관',
    transitInfo: '🚌 시내버스 1000번, 119번 탑승 ➔ "전동성당" 하차 (경기전 내 도보 3분)',
    parkingInfo: '🚗 주차장: 경기전 리베라 주차장 / 한옥마을 제1공영주차장',
  },

  // --- [2] 역사 & 명소 (야외/실내) ---
  {
    name: '전동성당',
    category: '실내 · 역사 명소',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 0,
    reason: '현재 위치에서 가장 가까운 전주의 대표 역사 사적지입니다.',
    isMustVisit: true,
    isIndoor: true,
    mapX: 30,
    mapY: 62,
    address: '전북 전주시 완산구 태조로 51',
    operatingHours: '09:00 - 17:00 (일요일 미사 시간 제외)',
    phone: '063-284-3222',
    tags: ['#사적지', '#사진맛집', '#비잔틴양식', '#한옥마을입구'],
    suggestedDuration: '30분',
    tips: '💡 현지인 팁: 성당 본당 정면도 예쁘지만, 뒤편 사제관 건물과 성모상 앞 정원이 한적한 숨은 포토존입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20전동성당',
    transitInfo: '🚌 시내버스 1000번(명품버스), 119번, 535번 탑승 ➔ "전동성당·한옥마을" 정류장 하차 (도보 2분)',
    parkingInfo: '🚗 주차장: 한옥마을 제1공영주차장 (전북 전주시 완산구 기린대로 99) · 기본 30분 1,000원',
  },
  {
    name: '경기전',
    category: '실외 · 역사 문화 (지하 어진박물관 연계)',
    cost: 3000,
    costLabel: '3,000원',
    walkMinutes: 4,
    reason: '태조 이성계의 어진이 모셔진 곳으로, 대나무 숲길과 지하 어진박물관을 함께 둘러보는 스팟입니다.',
    isMustVisit: true,
    isIndoor: false,
    mapX: 38,
    mapY: 55,
    address: '전북 전주시 완산구 태조로 44',
    operatingHours: '09:00 - 19:00 (입장마감 18:00)',
    phone: '063-281-2790',
    tags: ['#어진박물관', '#대나무숲', '#한복체험필수', '#역사탐방'],
    suggestedDuration: '1시간',
    tips: '💡 현지인 팁: 야외 구경 후 경기전 내부 시원한 지하 어진박물관으로 이동하시면 무더위를 싹 식힐 수 있습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20경기전',
    transitInfo: '🚌 시내버스 1000번, 119번, 6001번 탑승 ➔ "전동성당·한옥마을" 하차 후 태조로 따라 도보 3분',
    parkingInfo: '🚗 주차장: 경기전 리베라 부설 주차장 또는 한옥마을 제2공영주차장 이용 권장',
  },
  {
    name: '오목대',
    category: '실외 · 전망 명소 (폭염 시 주의)',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 8,
    reason: '한옥마을 전체 기와지붕 풍경을 한눈에 내려다볼 수 있는 대표 전망 포인트입니다.',
    isMustVisit: false,
    isIndoor: false,
    mapX: 50,
    mapY: 35,
    address: '전북 전주시 완산구 기린대로 55',
    operatingHours: '24시간 상시 개방',
    phone: '063-281-2114',
    tags: ['#한옥전망', '#야경명소', '#노을포인트', '#이성계'],
    suggestedDuration: '30분',
    tips: '💡 팁: 무더운 한낮보다는 선선한 저녁 일몰 시간대 방문하시거나 양산/손선풍기를 꼭 지참하세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20오목대',
    transitInfo: '🚌 시내버스 1000번, 190번 탑승 ➔ "오목대·자만벽화마을" 정류장 하차 (도보 3분 계단)',
    parkingInfo: '🚗 주차장: 오목대 관광지 공영주차장 (기린대로 55 부근 노상 주차)',
  },
  {
    name: '자만벽화마을',
    category: '실외 · 예술 골목 (경사로 주의)',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 14,
    reason: '오목대 건너편 산자락 골목에 알록달록한 아기자기한 벽화와 전망 좋은 카페들이 모여있습니다.',
    isMustVisit: false,
    isIndoor: false,
    mapX: 82,
    mapY: 65,
    address: '전북 전주시 완산구 자만동2길 22',
    operatingHours: '상시 개방',
    phone: '063-281-2555',
    tags: ['#골목벽화', '#전망카페', '#사진스팟', '#레트로감성'],
    suggestedDuration: '50분',
    tips: '💡 팁: 경사로 오르막길이 있으므로 무더위 한낮에는 골목 상단의 시원한 음료 카페테라스 휴식을 추천합니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/자만벽화마을',
    transitInfo: '🚌 시내버스 1000번, 190번, 535번 탑승 ➔ "자만벽화마을" 정류장 하차 (육교 도보 2분)',
    parkingInfo: '🚗 주차장: 자만벽화마을 입구 노상 공영주차구역 (무료 주차 공간 다수)',
  },

  // --- [3] 네이버 지도 연동 시원한 점심/미식 맛집 ---
  {
    name: '한국집 (전주 3대 비빔밥)',
    category: '🍽️ 네이버 지도 추천 · 실내 점심 식사',
    cost: 15000,
    costLabel: '15,000원',
    walkMinutes: 5,
    reason: '미슐랭 가이드에 등재된 70년 전통의 전주 전통 육회비빔밥 맛집입니다.',
    isMustVisit: false,
    isMeal: true,
    isIndoor: true,
    mapX: 35,
    mapY: 50,
    address: '전북 전주시 완산구 어진길 119',
    operatingHours: '09:30 - 21:00 (브레이크타임 16:00 - 17:00)',
    phone: '063-284-2230',
    tags: ['#전주비빔밥', '#미슐랭가이드', '#육회비빔밥', '#시원한점심'],
    suggestedDuration: '50분',
    tips: '💡 네이버 지도 점심 팁: 시원한 실내에서 놋그릇에 담겨 나오는 육회비빔밥과 정갈한 반찬을 즐기세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20한국집',
    transitInfo: '🚌 시내버스 1000번, 119번 탑승 ➔ "전동성당" 하차 후 어진길 방향 도보 3분',
    parkingInfo: '🚗 주차장: 한국집 전용 무료 주차장 보유 (식사 고객 무료 주차 가능)',
  },
  {
    name: '현대옥 한옥마을점 (콩나물국밥)',
    category: '🍽️ 네이버 지도 추천 · 실내 점심/식사',
    cost: 9000,
    costLabel: '9,000원',
    walkMinutes: 7,
    reason: '남부시장식 수란과 함께 즐기는 전주 콩나물국밥의 대표 식당입니다.',
    isMustVisit: false,
    isMeal: true,
    isIndoor: true,
    mapX: 42,
    mapY: 45,
    address: '전북 전주시 완산구 오목대길 66',
    operatingHours: '08:00 - 20:00 (연중무휴)',
    phone: '063-285-8989',
    tags: ['#콩나물국밥', '#남부시장식', '#수란', '#든든한식사'],
    suggestedDuration: '40분',
    tips: '💡 네이버 지도 점심 팁: 쾌적한 실내에서 남부시장식 시원칼칼한 콩나물국밥과 수란을 맛보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/현대옥%20한옥마을점',
    transitInfo: '🚌 시내버스 1000번, 535번 탑승 ➔ "오목대·한옥마을" 하차 후 오목대길 도보 4분',
    parkingInfo: '🚗 주차장: 한옥마을 제2공영주차장 이용 권장',
  },
  {
    name: '조점례 남부시장 피순대',
    category: '🍽️ 네이버 지도 추천 · 실내 미식 식당',
    cost: 10000,
    costLabel: '10,000원',
    walkMinutes: 12,
    reason: '속이 꽉 찬 수제 피순대와 얼큰한 순대국밥으로 전국적인 명성을 얻은 전주 미식 스팟입니다.',
    isMustVisit: false,
    isMeal: true,
    isIndoor: true,
    mapX: 75,
    mapY: 42,
    address: '전북 전주시 완산구 풍남문2길 39 (남부시장 내)',
    operatingHours: '24시간 영업 (연중무휴)',
    phone: '063-288-1439',
    tags: ['#피순대', '#순대국밥', '#남부시장맛집', '#TV출연맛집'],
    suggestedDuration: '50분',
    tips: '💡 네이버 지도 점심 팁: 깻잎에 피순대와 초장을 올려 싸 드시는 것이 전주 현지 방식입니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/조점례%20남부시장%20피순대',
    transitInfo: '🚌 시내버스 684번, 74번, 89번, 104번 탑승 ➔ "남부시장" 하차 (시장 입구 도보 2분)',
    parkingInfo: '🚗 주차장: 남부시장 천변 공영주차장 (전북 전주시 완산구 천변오송로 9) / 1시간 무료 할인권',
  },
  {
    name: '교동떡갈비',
    category: '🍽️ 네이버 지도 추천 · 떡갈비 점심',
    cost: 16000,
    costLabel: '16,000원',
    walkMinutes: 6,
    reason: '숯불 향 가득한 수제 떡갈비와 전주 비빔밥 세트를 쾌적한 한옥 공간에서 즐기는 맛집입니다.',
    isMustVisit: false,
    isMeal: true,
    isIndoor: true,
    mapX: 48,
    mapY: 52,
    address: '전북 전주시 완산구 은행로 52',
    operatingHours: '11:00 - 20:30 (라스트오더 19:50)',
    phone: '063-288-2232',
    tags: ['#수제떡갈비', '#한옥맛집', '#점심세트', '#에어컨쾌적'],
    suggestedDuration: '55분',
    tips: '💡 네이버 지도 점심 팁: 런치 시간대 떡갈비+미니비빔밥 정식 세트 구성의 가성비가 뛰어납니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20교동떡갈비',
    transitInfo: '🚌 시내버스 1000번, 119번 탑승 ➔ "전동성당" 하차 후 은행로 따라 도보 5분',
    parkingInfo: '🚗 주차장: 교동 떡갈비 제휴 한옥마을 제1공영주차장 이용 권장',
  },

  // --- [4] 디저트 & 시원한 음료 ---
  {
    name: '외할머니솜씨 (흑임자 팥빙수)',
    category: '🍧 시원한 실내 · 디저트 카페',
    cost: 8000,
    costLabel: '8,000원',
    walkMinutes: 8,
    reason: '더위를 날려줄 시원 고소한 흑임자와 국내산 팥이 듬뿍 들어간 전주 한옥마을 대표 디저트 카페입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 55,
    mapY: 50,
    address: '전북 전주시 완산구 오목대길 81-8',
    operatingHours: '11:00 - 21:00 (월요일 휴무)',
    phone: '063-232-5804',
    tags: ['#흑임자빙수', '#시원한빙수', '#블루리본', '#전통디저트'],
    suggestedDuration: '40분',
    tips: '💡 팁: 시원한 에어컨 아래에서 시그니처 메뉴인 옛날 흑임자 팥빙수를 드시며 더위를 식혀보세요.',
    naverMapUrl: 'https://map.naver.com/v5/search/전주%20외할머니솜씨',
    transitInfo: '🚌 시내버스 1000번, 190번 탑승 ➔ "오목대" 하차 (도보 5분)',
    parkingInfo: '🚗 주차장: 한옥마을 제2공영주차장 (오목대 부근) 도보 4분',
  },
  {
    name: '국립무형유산원 전시관',
    category: '🏛️ 시원한 대형 실내 · 국립 전시관',
    cost: 0,
    costLabel: '무료',
    walkMinutes: 12,
    reason: '대한민국 무형유산의 역사와 전통 장인들의 작품을 서늘하고 쾌적하게 관람하는 대형 실내 박물관입니다.',
    isMustVisit: false,
    isIndoor: true,
    mapX: 58,
    mapY: 75,
    address: '전북 전주시 완산구 서학로 95',
    operatingHours: '09:30 - 17:30 (매주 월요일 휴무)',
    phone: '063-280-1400',
    tags: ['#무형유산', '#무료전시', '#에어컨피서', '#쾌적한실내'],
    suggestedDuration: '1시간 10분',
    tips: '💡 팁: 무더위를 완전히 피해 대형 실내 전시실에서 조용하고 쾌적한 피서 관람을 즐길 수 있습니다.',
    naverMapUrl: 'https://map.naver.com/v5/search/국립무형유산원',
    transitInfo: '🚌 시내버스 190번, 5000번 탑승 ➔ "국립무형유산원" 정류장 하차 (도보 1분)',
    parkingInfo: '🚗 주차장: 국립무형유산원 전용 대형 지하/지상 무료 주차장 보유',
  },
]

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const q = searchParams.get('q')?.trim() ?? ''

  if (!q) {
    return NextResponse.json(JEONJU_PLACES_DATABASE.slice(0, 10))
  }

  const matched = JEONJU_PLACES_DATABASE.filter(
    (p) =>
      p.name.toLowerCase().includes(q.toLowerCase()) ||
      p.category.toLowerCase().includes(q.toLowerCase()) ||
      p.address?.toLowerCase().includes(q.toLowerCase()) ||
      p.tags?.some((t) => t.toLowerCase().includes(q.toLowerCase())),
  )

  if (!matched.some((p) => p.name === q)) {
    const customSearchPlace: Omit<Place, 'id' | 'order'> = {
      name: q,
      category: '네이버 지도 검색 장소',
      cost: 0,
      costLabel: '입장료/비용 개별 확인',
      walkMinutes: 10,
      reason: `사용자께서 직접 검색하여 추가하신 필수 방문지 '${q}'입니다.`,
      isMustVisit: true,
      isIndoor: true,
      mapX: Math.floor(Math.random() * 40) + 30,
      mapY: Math.floor(Math.random() * 40) + 30,
      address: `전북 전주시 완산구 ${q} 부근 (네이버 지도 검색)`,
      operatingHours: '운영시간 개별 확인',
      phone: '네이버 지도 참조',
      tags: ['#직접검색추가', '#필수방문지', '#네이버지도'],
      suggestedDuration: '45분',
      tips: `💡 현지인 팁: 네이버 지도를 통해 '${q}'의 최신 휴무일과 실시간 방문 후기를 확인하세요.`,
      naverMapUrl: `https://map.naver.com/v5/search/${encodeURIComponent(q)}`,
      transitInfo: `🚌 시내버스 노선은 네이버 지도의 최신 버스 정보를 참조해 주세요.`,
      parkingInfo: `🚗 인근 공영/민영 주차장을 이용해 주세요.`,
    }
    return NextResponse.json([customSearchPlace, ...matched].slice(0, 10))
  }

  return NextResponse.json(matched.slice(0, 10))
}
